import type { AccessGrantId, BusinessId, FactId, OperationId, UserId } from '@/domain/shared/ids'

/**
 * Identifiers are generated by the application, never by the database. A caller
 * that has to retry an operation can therefore reuse the same ids.
 */
export interface IdGenerator {
  businessId(): BusinessId
  userId(): UserId
  accessGrantId(): AccessGrantId
  factId(): FactId
  operationId(): OperationId
}
